using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Axion.Scripting;

/// <summary>
/// Emits a complete C# class (subclassing Axion.Core.Behavior) from the shared AST.
/// The Roslyn-based ScriptHost compiles this into a .NET assembly at runtime.
/// </summary>
public static class CSharpEmitter
{
    public sealed class Options
    {
        /// <summary>Generated C# class name. Unity-style: PascalCase from filename.</summary>
        public string ClassName { get; set; } = "GeneratedScript";
        /// <summary>Namespace; defaults to "Axion.Scripts.Generated".</summary>
        public string Namespace { get; set; } = "Axion.Scripts.Generated";
        /// <summary>If true, emit as a Behavior subclass (engine script). Else, emit a static console-style class.</summary>
        public bool AsBehavior { get; set; } = true;
    }

    public static string Emit(ProgramNode p, Options? opts = null)
    {
        opts ??= new Options();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Axion CSharpEmitter");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine("using Axion.Core;");
        foreach (var s in p.Body) if (s is ImportStmt im) sb.AppendLine($"using {im.Path.Trim('"','\'')};");
        sb.AppendLine();
        sb.AppendLine($"namespace {opts.Namespace};");
        sb.AppendLine();

        var bodyStmts  = p.Body.Where(s => s is not FuncDecl && s is not ImportStmt && s is not CommentStmt).ToList();
        var funcs      = p.Body.OfType<FuncDecl>().ToList();
        bool hasStart  = funcs.Any(f => f.Name.Equals("start", System.StringComparison.OrdinalIgnoreCase));
        bool hasUpdate = funcs.Any(f => f.Name.Equals("loop",  System.StringComparison.OrdinalIgnoreCase) ||
                                          f.Name.Equals("update",System.StringComparison.OrdinalIgnoreCase));

        if (opts.AsBehavior)
        {
            sb.AppendLine($"public sealed class {opts.ClassName} : Behavior");
            sb.AppendLine("{");
            // Inline top-level statements as Awake() body when there is no explicit start/loop:
            if (!hasStart && !hasUpdate && bodyStmts.Count > 0)
            {
                sb.AppendLine("    public override void Start()");
                sb.AppendLine("    {");
                foreach (var s in bodyStmts) EmitStmt(s, 2, sb);
                sb.AppendLine("    }");
            }
            else if (bodyStmts.Count > 0)
            {
                // place top-level into Start, then user can also have own start
                sb.AppendLine("    public override void Awake()");
                sb.AppendLine("    {");
                foreach (var s in bodyStmts) EmitStmt(s, 2, sb);
                sb.AppendLine("    }");
            }

            foreach (var f in funcs)
            {
                var nm = f.Name.ToLowerInvariant();
                bool isStart  = nm == "start";
                bool isUpdate = nm == "loop" || nm == "update";
                sb.AppendLine();
                if (isStart)
                {
                    sb.AppendLine("    public override void Start()");
                    sb.AppendLine("    {");
                    foreach (var s in f.Body) EmitStmt(s, 2, sb);
                    sb.AppendLine("    }");
                }
                else if (isUpdate)
                {
                    sb.AppendLine("    public override void Update()");
                    sb.AppendLine("    {");
                    foreach (var s in f.Body) EmitStmt(s, 2, sb);
                    sb.AppendLine("    }");
                }
                else
                {
                    var pars = string.Join(", ", f.Params.Select(p => "dynamic " + p));
                    sb.AppendLine($"    private dynamic {f.Name}({pars})");
                    sb.AppendLine("    {");
                    foreach (var s in f.Body) EmitStmt(s, 2, sb);
                    sb.AppendLine("        return null;");
                    sb.AppendLine("    }");
                }
            }
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine($"public static class {opts.ClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Main(string[] args)");
            sb.AppendLine("    {");
            foreach (var s in bodyStmts) EmitStmt(s, 2, sb);
            sb.AppendLine("    }");
            foreach (var f in funcs)
            {
                var pars = string.Join(", ", f.Params.Select(p => "dynamic " + p));
                sb.AppendLine($"    static dynamic {f.Name}({pars})");
                sb.AppendLine("    {");
                foreach (var s in f.Body) EmitStmt(s, 2, sb);
                sb.AppendLine("        return null;");
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    private static string Ind(int n) => new(' ', n * 4);

    private static void EmitStmt(Stmt s, int lvl, StringBuilder sb)
    {
        var ind = Ind(lvl);
        switch (s)
        {
            case CommentStmt c:  sb.AppendLine($"{ind}// {c.Text}"); break;
            case ImportStmt:     break;
            case VarDecl v:
            {
                var rhs = EmitExpr(v.Value!);
                var ty  = !string.IsNullOrEmpty(v.Type) ? v.Type : InferType(v.Value);
                sb.AppendLine($"{ind}{ty} {v.Name} = {rhs};"); break;
            }
            case Assign a:       sb.AppendLine($"{ind}{EmitExpr(a.Target)} = {EmitExpr(a.Value)};"); break;
            case ExprStmt es:    sb.AppendLine($"{ind}{EmitExpr(es.Expr)};"); break;
            case ReturnStmt r:   sb.AppendLine($"{ind}return{(r.Values.Count > 0 ? " " + EmitExpr(r.Values[0]) : "")};"); break;
            case BreakStmt:      sb.AppendLine($"{ind}break;"); break;
            case ContinueStmt:   sb.AppendLine($"{ind}continue;"); break;
            case CrashStmt cr:   sb.AppendLine($"{ind}throw new Exception({(cr.Reason != null ? EmitExpr(cr.Reason) : "\"crash\"")});"); break;
            case IfStmt iff:
                sb.AppendLine($"{ind}if ({EmitExpr(iff.Cond)})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in iff.Then) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}");
                foreach (var (ec, eb) in iff.Elifs)
                {
                    sb.AppendLine($"{ind}else if ({EmitExpr(ec)})");
                    sb.AppendLine($"{ind}{{");
                    foreach (var t in eb) EmitStmt(t, lvl + 1, sb);
                    sb.AppendLine($"{ind}}}");
                }
                if (iff.Else != null) { sb.AppendLine($"{ind}else"); sb.AppendLine($"{ind}{{"); foreach (var t in iff.Else) EmitStmt(t, lvl + 1, sb); sb.AppendLine($"{ind}}}"); }
                break;
            case WhileStmt w:
                sb.AppendLine($"{ind}while ({EmitExpr(w.Cond)})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in w.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            case LoopStmt lp:
                sb.AppendLine($"{ind}while (true)");
                sb.AppendLine($"{ind}{{");
                foreach (var t in lp.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            case ForStmt f:
            {
                string init = f.Init is VarDecl iv ? $"int {iv.Name} = {EmitExpr(iv.Value!)}" : "";
                string step = f.Step is VarDecl sv ? $"{sv.Name} = {EmitExpr(sv.Value!)}" : "";
                string cond = f.Cond != null ? EmitExpr(f.Cond) : "true";
                sb.AppendLine($"{ind}for ({init}; {cond}; {step})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in f.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            }
            case ForEachStmt fe:
                sb.AppendLine($"{ind}foreach (var {fe.VarName} in {EmitExpr(fe.Iterable)})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in fe.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            case MatchStmt m:
                sb.AppendLine($"{ind}switch ({EmitExpr(m.Subject)})");
                sb.AppendLine($"{ind}{{");
                foreach (var (pat, body) in m.Cases)
                {
                    sb.AppendLine($"{ind}    case var __c when __c.Equals({EmitExpr(pat)}):");
                    foreach (var t in body) EmitStmt(t, lvl + 2, sb);
                    sb.AppendLine($"{ind}        break;");
                }
                if (m.Else != null) { sb.AppendLine($"{ind}    default:"); foreach (var t in m.Else) EmitStmt(t, lvl + 2, sb); sb.AppendLine($"{ind}        break;"); }
                sb.AppendLine($"{ind}}}"); break;
        }
    }

    private static string EmitExpr(Expr e) => e switch
    {
        NumLit n => n.Value.Contains('.') ? n.Value + "f" : n.Value,
        StrLit s => s.Value,
        BoolLit b => b.Value ? "true" : "false",
        NullLit => "null",
        VarRef v => MapBuiltin(v.Name),
        BinOp b when b.Op == "^" => $"(float)Math.Pow({EmitExpr(b.Left)}, {EmitExpr(b.Right)})",
        BinOp b => $"({EmitExpr(b.Left)} {b.Op} {EmitExpr(b.Right)})",
        UnaryOp u => $"{u.Op}{EmitExpr(u.Operand)}",
        CallExpr c => EmitCall(c),
        MemberExpr m => $"{EmitExpr(m.Target)}.{m.Member}",
        IndexExpr ix => $"{EmitExpr(ix.Target)}[{EmitExpr(ix.Index)}]",
        ListLit l => $"new List<dynamic>{{ {string.Join(", ", l.Items.Select(EmitExpr))} }}",
        RangeExpr r => $"Enumerable.Range({EmitExpr(r.Start)}, ({EmitExpr(r.End)}) - ({EmitExpr(r.Start)}))",
        _ => "/*expr*/",
    };

    private static string EmitCall(CallExpr c)
    {
        if (c.Callee is VarRef v)
        {
            switch (v.Name)
            {
                case "print":          return $"Log.Info({Args(c.Args)})";
                case "rem":            return $"({EmitExpr(c.Args[0])} % {EmitExpr(c.Args[1])})";
                case "percent":        return $"({EmitExpr(c.Args[0])} / 100f * {EmitExpr(c.Args[1])})";
                case "convert":        return $"Convert.ChangeType({EmitExpr(c.Args[0])}, typeof({EmitExpr(c.Args[1])}))";
                case "quit":           return $"throw new Exception({(c.Args.Count > 0 ? EmitExpr(c.Args[0]) : "\"quit\"")})";
            }
        }
        if (c.Callee is MemberExpr me && me.Target is VarRef vt && vt.Name == "print")
        {
            return me.Member switch
            {
                "console" => $"Console.WriteLine({Args(c.Args)})",
                "log"     => $"Log.Info({Args(c.Args)})",
                _         => $"Log.Info({Args(c.Args)})",
            };
        }
        return $"{EmitExpr(c.Callee)}({Args(c.Args)})";
    }

    private static string Args(List<Expr> args) => string.Join(", ", args.Select(EmitExpr));

    private static string MapBuiltin(string name) => name switch
    {
        "true"  => "true",
        "false" => "false",
        "null" or "none" => "null",
        _ => name,
    };

    private static string InferType(Expr? v) => v switch
    {
        NumLit n => n.Value.Contains('.') ? "float" : "int",
        StrLit  => "string",
        BoolLit => "bool",
        ListLit => "List<dynamic>",
        _ => "var",
    };
}
